### PR TITLE
Implemented Reviews, Main class revamp.

### PR DESCRIPTION
**Pull request by Syreldar**
**Chart class changes:**
1. Implemented `reviews` field and `chart.addReview()` method.

**Customer class changes:**
1. Implemented `customer.buyProduct()` overload for specific `Shop` objects in `Customer` class.

**Database class changes:**
1. Implemented `reviews` field and its getter method.
2. Added `productReviewCount` and `shopReviewCount` fields and their getter methods.
3. Added `addReview()`, `getReviewsForShop()`, `findProductByName()`, `findCustomerByName()` methods.
4. Added `registerReview` overloads for `Product` and `Shop` objects.
5. Added `getMostReviewedProduct()` and `getMostReviewedShop()` methods.

**Product class changes**
1. Renamed `quantity` field to `currentQuantity`.
2. Added `initialQuantity` field and its getter method.
3. Added `reviews` field and its getter method.
4. Added `getSoldAmount()` method.
5. Added `addReview()`, `getReviewCount()` and `getReviewsAverage()` methods.

**Review class:**
1. Implemented.

**ProductReview class (Review subclass):**
1. Implemented.

**ShopReview class (Review subclass):**
1. Implemented.

**Shop class changes:**
1. Streamlined `containsProduct()` method.
2. Added overload `containsProduct()` method for productName.
3. Added `addReview()`, `getReviewCount()` and `getReviewsAverage()` methods.
4. Added `getMostSoldProduct()` method.

**Main class changes:**
1. Revamped.
2. Split into multiple functions placed in the `Utilities` class.

**Utilities class:**
1. Added.

### CODE REVIEW

**Review by Andrea2423 — APPROVED** [review]
Per me va bene i commit sono dettagliati mi sono dovuto cercare alcune cose, come è giusto che sia, per il resto ringrazio del contributo che stai dando a questo progetto

**Comment by Morgoroth92** [comment]
Per me vanno bene i cambiamenti

**Review by Morgoroth92 — APPROVED** [review]
ok

**Review by Sara-hub96 — COMMENTED** [review]
Penso che va bene

**Pull request merged**
